version: '3.8'

services:
  user:
    build:
      context: ./userService
    image: microservice/user
    restart: "no"
    environment:
      - DB_URI=mongodb://mongo:27017/
      - DB_NAME=microservice_user
    ports:
      - 8080:50051
    depends_on:
      - mongo
    volumes:
      - ./userService/src:/app
      - /app/node_modules

  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_DATABASE: microservice_user
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    command: --quiet

volumes:
  postgresdb:
  mysqldb:
  mongodb:
  mongodb_config:
